# Generated by Django 4.2.5 on 2023-10-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('Situation', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True, verbose_name='Situation')),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('I lost my account', 'I lost my account'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50, verbose_name='Option'),
        ),
    ]
