# Generated by Django 4.2.5 on 2023-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_message_alter_support_situation_alter_support_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('I lost my account', 'I lost my account'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50, verbose_name='Person'),
        ),
    ]
