# Generated by Django 4.2.5 on 2023-10-11 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_message_situation_alter_support_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=55, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('I lost my account', 'I lost my account'), ('Others', 'Others'), ('Update resume', 'Update resume')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50, verbose_name='Person'),
        ),
    ]
