# Generated by Django 4.2.5 on 2023-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_message_email_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('Others', 'Others'), ('Update resume', 'Update resume'), ('I lost my account', 'I lost my account')], max_length=50, verbose_name='Option'),
        ),
    ]
