# Generated by Django 4.2.5 on 2023-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_notepad_alter_support_situation_alter_support_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.CharField(max_length=150, verbose_name='Frontend')),
                ('backend', models.CharField(max_length=150, verbose_name='Backend')),
                ('fullstack', models.CharField(max_length=150, verbose_name='Fullstack')),
                ('intern', models.CharField(max_length=150, verbose_name='Intern')),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('I lost my account', 'I lost my account'), ('Others', 'Others'), ('My password does not work', 'My password does not work')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50, verbose_name='Person'),
        ),
    ]
