# Generated by Django 4.2.5 on 2023-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_vacancies_alter_support_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(max_length=100, verbose_name='Timer')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('I lost my account', 'I lost my account'), ('Others', 'Others'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50, verbose_name='Person'),
        ),
    ]
