# Generated by Django 4.2.5 on 2023-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_countdown_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Intern', 'Intern')], max_length=150, verbose_name='Job Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('Situation', models.CharField(blank=True, choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50, null=True, verbose_name='Situation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('profile_document', models.FileField(max_length=500, upload_to='resume', verbose_name='Resume')),
                ('company_note', models.TextField(blank=True, null=True, verbose_name='Company Note')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('I lost my account', 'I lost my account'), ('Others', 'Others')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50, verbose_name='Person'),
        ),
    ]
