# Generated by Django 4.2.5 on 2023-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_waiting_alter_message_situation_alter_support_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('Others', 'Others'), ('I lost my account', 'I lost my account'), ('Update resume', 'Update resume')], max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='Situation',
            field=models.CharField(blank=True, choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='profile_document',
            field=models.FileField(upload_to='resume', verbose_name='Resume'),
        ),
    ]
